'use strict';

module.exports = {
    // flux
    AUDIO_CHANGE_EVENT: 'AUDIO_CHANGE_EVENT',
    CHANGE_WAVEFORM: 'CHANGE_WAVEFORM',
    CHANGE_AM_WAVEFORM: 'CHANGE_AM_WAVEFORM',
    CHANGE_AM_FREQUENCY: 'CHANGE_AM_FREQUENCY',
    CHANGE_GAIN: 'CHANGE_GAIN',
    CHANGE_SUSTAIN: 'CHANGE_SUSTAIN',
    CHANGE_DETUNE: 'CHANGE_DETUNE',
    CHANGE_ATTACK: 'CHANGE_ATTACK',
    CHANGE_DECAY: 'CHANGE_DECAY',
    CHANGE_RELEASE: 'CHANGE_RELEASE',
    // waveform
    INITIAL_WAVEFORM: 'square',
    // gain stuff
    INITIAL_GAIN_VALUE: 0.6,
      MAX_GAIN_VAL: 1,
      MIN_GAIN_VAL: 0,
      D_GAIN: 0.05,
      MINIMUM_GAIN_RAMP: 0.05,
    INITIAL_SUSTAIN: 0.5,
      MAX_SUSTAIN: 1,
      MIN_SUSTAIN: 0,
      D_SUSTAIN: 0.05,
    // envelope durations
    INITIAL_ATTACK: 0.1,
      MAX_ATTACK_DURATION: 0.75,
      MIN_ATTACK_DURATION: 0.0,
      D_ATTACK: 0.1,
    INITIAL_DECAY: 0.1,
      MAX_DECAY_DURATION: 0.75,
      MIN_DECAY_DURATION: 0.0,
      D_DECAY: 0.1,
    INITIAL_RELEASE: 0.5,
      MAX_RELEASE_DURATION: 0.75,
      MIN_RELEASE_DURATION: 0.0,
      D_RELEASE: 0.1,
    // detune
    INITIAL_DETUNE: 0,
      MAX_DETUNE_VAL: 1000,
      MIN_DETUNE_VAL: -1000,
      D_DETUNE: 50,
    // Amplitude Modulation
    INITIAL_AM_FREQUENCY: 0,
      MIN_AM_FREQUENCY: 0,
      MAX_AM_FREQUENCY: 40,
      INITIAL_AM_MULTIPLIER: 1,
      INITIAL_AM_WAVEFORM: 'sine'
  };
