'use strict';
module.exports = {
  ADD_RECORDING: 'ADD_RECORDING',
  DELETE_RECORDING: 'DELETE_RECORDING',
  UPDATE_RECORDING: 'UPDATE_RECORDING',
  RECORDING_CHANGE_EVENT: 'RECORDING_CHANGE_EVENT'
};
